"""Añadir columna token a registro

Revision ID: 4f201aeff43d
Revises: 
Create Date: 2025-02-18 21:51:24.848265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f201aeff43d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('token_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro', schema=None) as batch_op:
        batch_op.drop_column('token_expiry')
        batch_op.drop_column('token')

    # ### end Alembic commands ###
